#@TYPE: Machine
#@NAME: Altera SoCFPGA Agilex5
#@DESCRIPTION: Additional machine configuration for the Agilex5 SoCFPGA

IMAGE_TYPE:comet_a65 ?= "gsrd"

KERNEL_REPO = "git://github.com/terasic/linux-socfpga.git"
KERNEL_PROT = "https"

UBOOT_REPO = "git://github.com/terasic/u-boot-socfpga.git"
UBOOT_PROT = "https"

ATF_REPO = "git://github.com/terasic/arm-trusted-firmware.git"
ATF_PROT = "https"


MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append:comet_a65 = " \
		kernel-modules \
		kernel-devicetree \
		"
