#@TYPE: Machine
#@NAME: Terasic Comet A65
#@DESCRIPTION: Unified machine configuration for Terasic Comet A65 (SD Card/eMMC)

require conf/machine/include/socfpga_armv8-2a.inc
require conf/machine/include/ubifs_agilex5.inc

# base configurations
KBUILD_DEFCONFIG ?= "defconfig"
KERNEL_CLASSES:append = " kernel-fitimage"
KERNEL_IMAGETYPE = "Image"
FIT_KERNEL_COMP_ALG = "none"
SERIAL_CONSOLES ?= "115200;ttyS0"

# u-boot common configurations
UBOOT_CONFIG ??= "comet_a65-atf"
UBOOT_CONFIG[comet_a65-atf] = "socfpga_agilex5_comet_a65_defconfig"
UBOOT_BINARY = "u-boot.itb"
UBOOT_SUFFIX = "itb"
UBOOT_ENTRYPOINT = "0x4000000"
UBOOT_LOADADDRESS = "0x4000000"

UBOOT_EXTLINUX ?= "1"
UBOOT_EXTLINUX_LABELS ?= "default"
UBOOT_EXTLINUX_DEFAULT_LABEL ?= "Terasic Comet A65 SDMMC"

UBOOT_EXTLINUX_MENU_DESCRIPTION:default ?= "Terasic Comet A65 SDMMC"
UBOOT_EXTLINUX_KERNEL_IMAGE:default ?= "../${KERNEL_IMAGETYPE}"
UBOOT_EXTLINUX_FDTDIR:default ?= ".."
UBOOT_EXTLINUX_CONSOLE ?= "console=ttyS0,115200n8"
UBOOT_EXTLINUX_KERNEL_ARGS:default ?= "rootwait rw earlyprintk"
UBOOT_EXTLINUX_ROOT:default ?= "root=/dev/mmcblk0p2"


BOOT_MEDIUM ??= "sdmmc"

KERNEL_DEVICETREE = "intel/socfpga_agilex5_comet_a65.dtb \
					intel/socfpga_agilex5_comet_a65_emmc.dtb"


IMAGE_BOOT_FILES = " \
    ${UBOOT_BINARY} \
    Image \
	${@ 'socfpga_agilex5_comet_a65.dtb' if d.getVar('BOOT_MEDIUM') == 'sdmmc' else 'socfpga_agilex5_comet_a65_emmc.dtb;socfpga_agilex5_comet_a65.dtb'} \
	boot.scr.uimg \
"


WKS_FILE ?= "sdimage-stratix10-agilex.wks"
IMAGE_FSTYPES:append = " wic"
