#@TYPE: Machine
#@NAME: Intel SoCFPGA Stratix10
#@DESCRIPTION: Machine configuration for the Stratix 10 SoCFPGA

IMAGE_TYPE:titan_s10_som ?= "gsrd"

KERNEL_REPO = "git://github.com/terasic/linux-socfpga.git"
KERNEL_PROT = "https"

UBOOT_REPO = "git://github.com/terasic/u-boot-socfpga.git"
UBOOT_PROT = "https"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append:titan_s10_som = " \
		kernel-modules \
		device-tree \
		hw-ref-design \
		"

EXTRA_IMAGEDEPENDS:append:titan_s10_som = " u-boot-socfpga-scr"

IMAGE_BOOT_FILES:titan_s10_som = " \
		boot.scr.uimg \
		u-boot.itb \
		kernel.itb \
		"
